unbind C-b

bind-key C-a send-prefix

bind    r       source-file ~/.tmux.conf
bind -n M-Up    select-pane -U
bind -n M-Left  select-pane -L
bind -n M-Down  select-pane -D
bind -n M-Right select-pane -R
bind -n M-l     next-window
bind -n M-h     previous-window

set -g      mouse on
set -g -u   status-right
set -g      default-terminal "screen-256color"
set -g      status-right     "#h | Week %V | %Y-%m-%d %H:%M"

set-option -g prefix C-a
set-option -g allow-rename off
