# General
set -g default-terminal "screen-256color"
set-option -g allow-rename off

# Prefix & Reload
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind r source-file ~/.tmux.conf

# Navigation
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-h previous-window
bind -n M-l next-window

# Status Content
set -g status-left ""
set -g status-right-length 150
set -g status-right " Week %V | #S "
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# Theme
set -g status-style "fg=colour251,bg=colour236"
set -g window-status-style "fg=colour244,bg=colour236"
set -g window-status-current-style "fg=black,bg=blue,bold"
set -g pane-border-style "fg=colour236,bg=default"
set -g pane-active-border-style "fg=blue,bg=default"
set -g message-style "fg=black,bg=blue,bold"
